### ISSUE TITLE
[BUG] GWLB resource filter not returning correct arn

### ISSUE THREAD

**Issue by vainiusd** [prometheus-community/yet-another-cloudwatch-exporter#1345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

Yet Another CloudWatch Exporter version 0.57.0

### Config file

```yaml
  - type: gwlb
    regions:
      - eu-central-1
    roundingPeriod: 300
    period: 300
    length: 300
    delay: 300
    nilToZero: true
    addCloudwatchTimestamp: true
    recentlyActiveOnly: true
    statistics:
      - Sum
      - Maximum
      - SampleCount
    metrics:
      - name: ProcessedBytes
      - name: ActiveFlowCount
      - name: NewFlowCount
      - name: UnHealthyHostCount
        statistics: [ Maximum ]
      - name: HealthyHostCount
        statistics: [ Minimum ]
      - name: ConsumedLCUs
```

### Current Behavior

Only target group is discovered via resource filters and it's arn is added to metric labels as owner.
GWLB resource arn is not detected.

### Expected Behavior

GWLB arn is disovered and added to metrics as owner resource.

### Anything else?

Current resource filter is not supported. Supported filter list can be found here:
https://docs.aws.amazon.com/resource-explorer/latest/userguide/supported-resource-types.html#services-elasticloadbalancing

`elasticloadbalancing:loadbalancer/gwy` is not a supported resource filter.

Example redacted awscli output (only gwlb in that account):
```bash
$ aws resourcegroupstaggingapi get-resources --resource-type-filters elasticloadbalancing:loadbalancer
{
    "ResourceTagMappingList": [
        {
            "ResourceARN": "arn:aws:elasticloadbalancing:eu-central-1:123456789012:loadbalancer/gwy/GWLB-NAME/01234abcdef01234",
            "Tags": [
                {
                    "Key": "tag-key",
                    "Value": "tag-value"
                }
            ]
        }
    ]
}
$ aws resourcegroupstaggingapi get-resources --resource-type-filters elasticloadbalancing:loadbalancer/gwy
{
    "ResourceTagMappingList": []
}
```

Required changes:
1. Reverting https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/90ee557545f5efa4f6e414a31f558a89be7539c4/pkg/config/services.go#L447 to `elasticloadbalancing:loadbalancer`.
2. Maybe remove target group from resource filters at all https://github.com/nerdswords/yet-another-cloudwatch-exporter/blob/90ee557545f5efa4f6e414a31f558a89be7539c4/pkg/config/services.go#L448?

If understood correctly, resource detection is required to map owner arn to the metric. Detecting only GWLB resource would suffice because metric dimenssion sets are:
- GWLB
- GWLB, AZ
- GWLB, TG
- GWLB, AZ, TG

So all metrics would have arn attached to them - all metrics belong only to GWLB resource

A broader resource detection filter would only end up retrieving more arns, but on the list metrics requests namespace is limited and metrics with other type of LBs will not come up, therefore no additional queries that cost would be generated, right?
