### ISSUE TITLE
[FEATURE] multiple scratping-interval in one yace

### ISSUE THREAD

**Issue by JetSquirrel** [prometheus-community/yet-another-cloudwatch-exporter#1346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have set up metrics scraping interval some  as 1-min and some as 5-interval,
I deploy to service: fast-yace and low-yace.

So can we configuration differece scraping-interal in one yace service?

For example, set up interval as Prometheus parameter:
```yaml
- job_name: fast_yace
  params: 
      interval: 1m
- job_name: slow_yace
  params: 
      interval: 5m
```

### What might the configuration look like?

None

**Comment by elshirak** [comment]
Hello!

Thanks for reporting this — I’m facing a similar issue and also find this enhancement quite necessary.

I'm using YACE to scrape metrics from AWS S3 and a VPN service. Since the VPN metrics are more time-sensitive, I’d like to scrape them more frequently than the S3 metrics.
Is it possible to configure different scraping intervals for these two jobs?

```
apiVersion: v1alpha1
discovery:
  jobs:
    - type: AWS/S3
      metrics:
        - name: BucketSizeBytes
          statistics:
            - Average

    - type: AWS/VPN
      metrics:
        - name: TunnelDataOut
          statistics:
            - Sum
        - name: TunnelDataIn
          statistics:
            - Sum
```
