### ISSUE TITLE
What should I add in config to get metrics with tags

### ISSUE THREAD

**Issue by Preeti011987** [prometheus-community/yet-another-cloudwatch-exporter#1403]
I have used config from 1 of the examples provided but I want something like:

##Info helper with tags
aws_elb_info{name="arn:aws:elasticloadbalancing:eu-west-1:472724724:loadbalancer/a815b16g3417211e7738a02fcc13bbf9",tag_KubernetesCluster="production-19",tag_Name="",tag_kubernetes_io_cluster_production_19="owned",tag_kubernetes_io_service_name="nginx-ingress/private-ext",region="eu-west-1"} 0
aws_ec2_info{name="arn:aws:ec2:eu-west-1:472724724:instance/i-someid",tag_Name="jenkins"} 0

in metrics. What shall I add in config.yaml to get something like tag_kubernetes/tag_name.
I did try options given in document such as custom_ta, search_tag, exportedtagonmetrics
But here I have to provide the tags, I want it to fetch tags automatically from AWS resource.
Is this possible?

**Comment by Preeti011987** [comment]
I have used config from 1 of the examples provided but I want something like:

### Info helper with tags
aws_elb_info{name="arn:aws:elasticloadbalancing:eu-west-1:472724724:loadbalancer/a815b16g3417211e7738a02fcc13bbf9",tag_KubernetesCluster="production-19",tag_Name="",tag_kubernetes_io_cluster_production_19="owned",tag_kubernetes_io_service_name="nginx-ingress/private-ext",region="eu-west-1"} 0
aws_ec2_info{name="arn:aws:ec2:eu-west-1:472724724:instance/i-someid",tag_Name="jenkins"} 0

in metrics. What shall I add in config.yaml to get something like tag_kubernetes/tag_name.
I did try options given in document such as custom_ta, search_tag, exportedtagonmetrics
But here I have to provide the tags, I want it to fetch tags automatically from AWS resource.
Is this possible?

**Comment by kgeckhart** [comment]
Are you asking how to add static data yourself? The Tags YACE pulls are straight from your AWS resources and it doesn't offer control over it. You can use prometheus relabeling to normalize inconsistent tags but it's all based on what your resources have.

**Comment by Jks08** [comment]
Hi @Preeti011987 , to get tags in your metrics I suggest adding the exportedTagsOnMetrics section to your config file. This is what a sample looks like:

```
apiVersion: v1alpha1
  discovery:
    exportedTagsOnMetrics:
      AWS/RDS:
        - MP_Engine
        - MP_MONITORING
        - MP_APPLICATION
        - MP_SERVICE    jobs:
      - type: AWS/RDS
        regions:
          - ap-south-1
        period: 300
        length: 300
        searchTags:
        - key: MP_MONITORING
          value: TRUE
        dimensionNameRequirements: [DBInstanceIdentifier]
        metrics:
          - name: CPUUtilization
            statistics: [Average]
          - name: MemoryUtilization
            statistics: [Average]
          - name: DatabaseConnections
            statistics: [Average]
          - name: FreeStorageSpace
            statistics: [Average]
          - name: DiskQueueDepth
            statistics: [Average]
          - name: SwapUsage
            statistics: [Average]
          - name: FreeableMemory
            statistics: [Average]
```

I have used the exportedTagsOnMetrics to get tags as labels in my metrics and I have also used searchTags to get the metrics only for those RDS which have the specific Tag Key and Value(in my case:  MP_MONITORING is the Key and TRUE is the Value).
