### ISSUE TITLE
Support mediapackagev2 discovery (AWS/MediaPackage)

### ISSUE THREAD

**Issue by henrylaiBrightcove** [prometheus-community/yet-another-cloudwatch-exporter#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Discovery currently doesn't find any tags for AWS/MediaPackage when only mediapackagev2 channels and channelgroups are used.

### What might the configuration look like?

```yml
discovery:
  jobs:
  - type: AWS/MediaPackage
    period: 30
    length: 600
    metrics:
    - name: EgressBytes
      statistics: [Sum]
  
```

### Anything else?

Current Error that shows is from discovery.go line 40:  No tagged resources made it through filtering.

I'd like to request a change to service.go line 617.
Add aws.String("mediapackagev2") to the list of resource filters.
