### ISSUE TITLE
[BUG] Not a valid metric name when using statistics with brackets like 'PR(:10)'

### ISSUE THREAD

**Issue by nixargh** [prometheus-community/yet-another-cloudwatch-exporter#1564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

0.61.2

### Config file

```yaml
discovery:
  jobs:
    - type: AWS/ELB
      regions:
        - eu-central-1
      period: 60
      length: 60
      dimensionNameRequirements:
        - AvailabilityZone
        - LoadBalancerName
      metrics:
        - name: Latency
          statistics: ["PR(:10)"]
```

### Current Behavior

Shows error, like:
```
$ curl -s http://localhost:5000/metrics
An error has occurred while serving metrics:

4 error(s) occurred:
* "aws_elb_latency_pr(_10)" is not a valid metric name
```

### Expected Behavior

Show metrics, like:
```
$ curl -s http://localhost:5000/metrics

aws_elb_latency_pr__10_{account_id="***...
```

### Anything else?

I've created the pull request - https://github.com/nerdswords/yet-another-cloudwatch-exporter/pull/1563
At least it works that way in my case.
