### ISSUE TITLE
[BUG] Metrics from PrivateLinkEndpoints not working

### ISSUE THREAD

**Issue by vitormazali** [prometheus-community/yet-another-cloudwatch-exporter#1579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### YACE version

v0.61.2

### Config file

apiVersion: v1alpha1
customNamespace:
  - name: VPCSubnetMetrics
    namespace: VPCSubnetMetrics
    regions:
      - us-east-1
    roles:
      - roleArn: arn:aws:iam::<account-id>:role/<role-name>
    dimensionNameRequirements:
      - AccountId
      - AccountAlias
      - SubnetId
      - SubnetName
      - VpcId
    delay: 240
    period: 300
    metrics:
      - name: TotalIps
        statistics:
          - Maximum
      - name: PercentAvailableIps
        statistics:
          - Minimum

##### new metrics of vpce #####

static:
  - namespace: AWS/PrivateLinkEndpoints
    name: vpc-endpoint
    regions:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - sa-east-1
    roles:
      - roleArn: arn:aws:iam::<account-id>:role/<role-name>
    metrics:
      - name: BytesProcessed
        statistics: [Sum,Average,Minimum,Maximum]
        period: 600
        length: 600
        nilToZero: true

### Current Behavior

the metrics obtained from `customNamespace` are ok, however, the ones from static are retuning only `NaN` values (0 after enabling nilToZero). We've tried different options, specifying dimensions, single region, same issue - example of config tested below:

    dimensions:
     - name: EndpointType
       value: Interface
     - name: ServiceName
       value: com.amazonaws.us-east-1.s3
     - name: SubnetId
       value: subnet-<subnet-id>
     - name: VPCEndpointId
       value: vpce-<vpce-id>
     - name: VPCId
       value: vpc-<vpc-id>
    metrics:
      - name: BytesProcessed
        statistics:
        - Maximum
        period: 600
        length: 600

### Expected Behavior

Have the same metric values that we are able to see in the Cloudwatch console (we do have metrics from VPC endpoints there) in the YACE.

**Comment by ahmedelmelegy** [comment]
I have the same issue that it can export metrics for PrivateLinkEndpoints
YACE version v0.61.2
```
                - type: AWS/PrivateLinkEndpoints
                  regions:
                    - eu-central-1
                  dimensionNameRequirements:
                    - Service Name
                  searchTags:
                    - key: Project
                      value: ^SOL$
                  metrics:
                    - name: PacketsDropped
                      statistics:
                        - Average
                        - Sum
                        - Maximum
                      period: 300    # 5-minute intervals, matching the reporting frequency
                      length: 900   # Query 15-minutes of data
                    - name: RstPacketsReceived
                      statistics:
                        - Average
                        - Sum
                        - Maximum
                      period: 300     # 5-minute intervals, matching the reporting frequency
                      length: 900   # Query 15-minutes of data`
```
