### ISSUE TITLE
[FEATURE] Documentation/Glue Example 

### ISSUE THREAD

**Issue by nick-at-UW** [prometheus-community/yet-another-cloudwatch-exporter#1591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

The documentation states that Glue metrics are available to be pulled via discovery, however I've been unable to get metrics from the Glue jobs. I've attempted to configure this via discovery job as well as customNamespace. For reference, the glue metrics we see do appear to be in a custom namespace called 'Glue'

I've provided a snippet of our config for reference. Any guidance in this configuration would be appreciated.

### What might the configuration look like?

```
    customNamespace:
      - name: Glue
        namespace: Glue
        regions:
          - us-west-2
        metrics:
          - name: glue.JobRunsSucceeded
            statistics: [Sum]
            period: 300
            length: 600
            delay: 300
            nilToZero: true
          - name: glue.JobRunsFailed
            statistics: [Sum]
            period: 300
            length: 600
            delay: 300
            nilToZero: true
    discovery:
      jobs:
        - type: Glue
          regions:
            - us-west-2
          metrics:
            - name: glue.JobRunsSucceeded
              statistics: [Sum]
              period: 300
              length: 600
              delay: 300
              nilToZero: true
            - name: glue.JobRunsFailed
              statistics: [Sum]
              period: 300
              length: 600
              delay: 300
              nilToZero: true

```

**Comment by asaednu** [comment]
@nick-at-UW were you able to get Glue metrics working with YACE ? 

I'm having the same issue where the only metric YACE has been able to export is `aws_glue_info`

**Comment by nick-at-UW** [comment]
I haven't had any luck with it. Still hopeful someone else has info and can
give some suggestions.

**Comment by asaednu** [comment]
@nick-at-UW  I was able to get this to work. The trick was to not use `customNamespace`. All you need is the `jobs` section. 

Also the name of the metrics were `glue.succeed.ALL` and `glue.error.ALL`. I used Cloudwatch Metrics in AWS Console to figure out the name of the metrics. 

So here is the snippet that works: 

```yaml
discovery:
  jobs:
    - type: Glue
      regions:
        - us-east-1
      addCloudwatchTimestamp: true
      period: 60
      length: 300
      delay: 60
      metrics:
        - name: glue.succeed.ALL
          statistics:
            - Sum
          nilToZero: true
        - name: glue.error.ALL
          statistics:
            - Sum
          nilToZero: true
  ```
