### ISSUE TITLE
[BUG] YACE doesn't send anything when it restarts on NIL values

### ISSUE THREAD

**Issue by afreyermuth98** [prometheus-community/yet-another-cloudwatch-exporter#1627]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### YACE version

0.60.0

### Current Behavior

I'm using YACE to export my cloudwatch metrics including AWS/ApplicationELB where I set nilToZero to get output even when there is no value in cloudwatch.
I'm checking the metric `HTTPCode_ELB_5XX_Count`. My metric is null for looooonnng time so I'm getting 0 in my prometheus values but it seems that when YACE restarts, it's losing his state and so as he has never seen this metric != null it does not send it anymore.

### Expected Behavior

The expected behaviour is that on restarts, the exporter continues to send 0 

### Steps To Reproduce

Have an ELB with a value that is always nil.
Have this in your config file 
```
- type: "AWS/ApplicationELB"
    regions:
      - YOUR_REGION
    period: 60
    length: 300
    delay: 30
    addCloudwatchTimestamp: false
    includeContextOnInfoMetrics: true
    searchTags:
      - key: Name
        value: .*
    metrics:
      - name: HTTPCode_ELB_5XX_Count
        statistics:
          - Sum
        nilToZero: true
```
When you have zero for long time (or not ? didn't try), restart your exporter and see that you do not have value anymore
