### ISSUE TITLE
[FEATURE] Filter based on ARN

### ISSUE THREAD

**Issue by woehrl01** [prometheus-community/yet-another-cloudwatch-exporter#1644]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

I understand that currently, filtering is only possible by using `searchTags`. I want to propose filtering also by ARN (with a regex)

### What might the configuration look like?

```yaml
discovery:
  jobs:
    - type: AWS/SQS
      regions:
        - eu-west-1
      searchArn:
        - stuff-.+
```
