### ISSUE TITLE
[BUG] YACE does not correctly retrieve sparse metrics like KMS CreateKey CallCount

### ISSUE THREAD

**Issue by harshpadhye** [prometheus-community/yet-another-cloudwatch-exporter#1677]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### YACE version

v0.61.2

### Current Behavior

We are experiencing an issue where YACE fails to accurately retrieve the CallCount metric for the KMS CreateKey operation. While the metric values are visible in CloudWatch, YACE consistently returns 0 even when the CallCount is non-zero within a given period. The creation of the KMS key is infrequent and sporadic.

### Expected Behavior

When querying the CallCount metric over a specified length, we expect YACE to return a positive, non-zero aggregate value (for Maximum, Average, and Sum) if a KMS key was indeed during that length of time.

### Steps To Reproduce

1. Run YACE with a scrape interval of 300, length of 300, and period <= length
2. Monitor live view of the Max, Average, and Sum values of KMS CreateKey CallCount metric
3. Create KMS Key in AWS console
4. Confirm metric exists and has value > 0 in CloudWatch
5. Monitor metric and notice it remains 0 across several scrape intervals

### Anything else?

**Root Cause (Suspected):**

Based on the code in pkg/clients/cloudwatch/v2/client.go here: https://github.com/prometheus-community/yet-another-cloudwatch-exporter/blob/f5ddcf4323dc97034491114d4074ae672cfc411f/pkg/clients/cloudwatch/v2/client.go#L145-L156 and the associated test example: https://github.com/prometheus-community/yet-another-cloudwatch-exporter/blob/master/pkg/clients/cloudwatch/v2/client_test.go#L28-L80 it appears that YACE might be retrieving only the first data point returned by CloudWatch for a given metric query. For sparse metrics like CallCount, if the first data point within the requested period is 0 (because no event occurred precisely at that timestamp), YACE will report 0, even if subsequent data points within the same period are non-zero.

This has been noticed by other users as well: https://github.com/prometheus-community/yet-another-cloudwatch-exporter/issues/865#issuecomment-2342070465

**Comment by seyhello** [comment]
Hi!

We are facing the same behavior also for the Lambda metrics (Invocations, Errors, etc ...). Some of our Lambdas are invoked once per hour and we are still getting NaN or 0 (if we set nilToZero parameter) in the scraped metrics. Attaching outputs from Cloudwatch directly and scraped YACE metric.

**Cloudwatch:**
![Image](https://github.com/user-attachments/assets/197fc0d2-3b1f-4c1e-a891-0fda6aa1aa5f)

**YACE:**
![Image](https://github.com/user-attachments/assets/52f446b6-898a-4fce-a289-4a0e73ee8c9f)

**YACE configuration:**
```
apiVersion: v1alpha1
sts-region: us-east-1
discovery:
  jobs:
  - type: AWS/Lambda
    regions:
      - us-east-1
    period: 300
    length: 300
    nilToZero: true
    roles:
      - ... ommited ...
    dimensionNameRequirements:
      - FunctionName
    metrics:
      - name: Invocations
        statistics: [Sum]
      - name: Errors
        statistics: [Sum]
      - name: Throttles
        statistics: [Sum]
      - name: Duration
        statistics: [Average, Maximum, Minimum, p90]
```
We have also set:
- YACE scraping interval (how often AWS metrics are scraped by YACE) - 60s
- ServiceMonitor scraping interval (How often Prometheus metrics are scraped from YACE endpoint) - 30s

Many thanks for help!

Kamil
