### ISSUE TITLE
[BUG] Autodiscovery job fails for services with special characters

### ISSUE THREAD

**Issue by albertoCrego** [prometheus-community/yet-another-cloudwatch-exporter#1692]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### YACE version

v0.62.1

### Config file

```
    apiVersion: v1alpha1
    sts-region: eu-central-1
    discovery:
      jobs:
      - type: AWS/SQS
        regions:
          - eu-central-1
        dimensionNameRequirements:
          - QueueName
        metrics:
          - name: ApproximateNumberOfMessagesVisible
            statistics:
            - Average
          - name: ApproximateNumberOfMessagesNotVisible
            statistics:
            - Average
          - name: NumberOfMessagesReceived
            statistics:
            - Average
          - name: NumberOfMessagesDeleted
            statistics:
            - Average
          - name: NumberOfMessagesSent
            statistics:
            - Average
        period: 600
        length: 600
        nilToZero: true
...ommited other jobs...
```

### Current Behavior

Only discover SQS without special characters. 

For example, discover SQS named `app-sqs` but not `my_application.fifo` or `my_second_application`

### Expected Behavior

Autodiscover every SQS, with any name. 

### Steps To Reproduce

1. Run the YACE over AWS Resources with "_" or "." 
2. Review the metrics scraped.
