### ISSUE TITLE
[BUG] ACM tags are not showing in Metrics

### ISSUE THREAD

**Issue by ravitejajasti** [prometheus-community/yet-another-cloudwatch-exporter#1705]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### YACE version

I used the below config to pull AWS tags for each certificate in the aws_certificatemanager_days_to_expiry_minimum metric. But its not working. 

I tried the samething with EC2 and was able to pull tags in EC2 prometheus metrics.

```
data:
  config.yml: |
    discovery:
      exportedTagsOnMetrics:
        AWS/EC2:
          - ClusterName
          - Creator
          - Vendor
          - ClusterId
          - Name
          - ResourceClass
          - management_service
        AWS/CertificateManager:
          - App
          - Name
          - QSE
          - ENV
          - CertType


      - type: AWS/CertificateManager
        resource_type: certificatemanager
        customTags:
          - key: name_account
            value: {{ cloudwatch_exporter.account_name }}
        regions: {{ cloudwatch_exporter.regions }}
        metrics:
          - name: DaysToExpiry
            statistics: [Minimum]
            period: 3600
            length: 86400
            dimensions:
              - CertificateArn
            rename_dimensions:
              CertificateArn: name
```

### Current Behavior

`aws_certificatemanager_days_to_expiry_minimum{account_alias="aws-dev", account_id="1234567890", app="***", custom_tag_name_account="aws-dev", dimension_CertificateArn="arn:aws:acm:us-east-1:******", instance="cloudwatch-exporter:9144", job="cloudwatch-exporter", name="global", region="us-east-1", snow_assignment_group="Support", team="support"}`

### Expected Behavior

Highlighted the new tags it should show

`aws_certificatemanager_days_to_expiry_minimum{account_alias="aws-dev", account_id="1234567890", app="***", custom_tag_name_account="aws-dev", dimension_CertificateArn="arn:aws:acm:us-east-1:******", instance="cloudwatch-exporter:9144", job="cloudwatch-exporter", name="global", region="us-east-1", snow_assignment_group="Support", team="support",

>  tag_Name="*********", tag_ENV="Prod", tag_App="*******"

}`

### Anything else?

it works perfectly fine for EC2 metrics. Highlighted the AWS tags

For Example,

`aws_ec2_network_in_sum{account_alias="aws-dev", account_id="*****", app="****", custom_tag_name_account="aws-dev", dimension_InstanceId="***, instance="cloudwatch-exporter:9144", job="cloudwatch-exporter", name="arn:aws:ec2:us-east-1:********", region="us-east-1", snow_assignment_group="Support", 

> tag_ClusterId="****", tag_ClusterName="power_analytics_dev_cluster", tag_Creator="***@****.com", tag_Name="workerenv-*****-33535146-*****-4b87-8809-8ceab107aad5-worker", tag_Vendor="****", tag_management_service="instance_manager_service", team="support"

}`
