### ISSUE TITLE
Custom Tag label dropped

### ISSUE THREAD

**Issue by bryan-kc** [prometheus-community/yet-another-cloudwatch-exporter#352]
I was trying to implement some custom labels for my ALBs based on the environment the ALB is running in

```
data:
  config.yml: |
    discovery:
      jobs:
      - regions:
        - us-east-1
        type: alb
        customTags:
          - key: KubernetesCluster
            value: my-prod-cluster
        metrics:
          - name: ActiveConnectionCount
            statistics:
            - Sum
            period: 300
            length: 3600
```

I've tried a variety of methods but it looks like the label is dropped in a weird way. For a given metric all of the labels are present except for the defined custom tag.

```
aws_alb_tg_target_connection_error_count_sum{custom_tag_="",dimension_LoadBalancer="xxx",dimension_TargetGroup="xxx",name="arn:aws:elasticloadbalancing:us-east-1:xxx",region="us-east-1"} 3
```

It looks like the value of the key and value from the yaml are being dropped somewhere but it's known that the customTag is defined so the string is empty.
