### ISSUE TITLE
0.31.0 scrape only 2 intervals

### ISSUE THREAD

**Issue by eilonmonday** [prometheus-community/yet-another-cloudwatch-exporter#467]
This is the first time we use the exporter, so we use 0.31.0-alpha
the issue is:
the  first 2 minutes the exporter is doing its job and success to scrape the SQS queue, but doesn't scrape anymore after it.
we use the flags:
```
 - "--config.file=/tmp/config.yml"
  - "--scraping-interval=60"
  - "--floating-time-window=true"
```

and the config:
```

  config.yml: |
    discovery:
      jobs:
      - regions:
        - us-east-1
        type: sqs
        enableMetricData: true
        searchTags:
        - key: scrape
          value: true
        metrics:
          - name: ApproximateNumberOfMessagesNotVisible
            statistics:
            - Average
            period: 60
            length: 60
            addCloudwatchTimestamp: true
          - name: NumberOfMessagesDeleted
            statistics:
            - Sum
            period: 60
            length: 120
            addCloudwatchTimestamp: true
            decoupled-scraping: false
```

we do see that the counter(yace_cloudwatch_requests_total) is increasing 

and you can see in the logs that it scrapes only during the first 2 intervals

```
{"level":"info","msg":"{\n  MetricDataResults: [{\n      Id: \"id_6941261091797652072\",\n      Label: \"ApproximateNumberOfMessagesNotVisible\",\n      StatusCode: \"Complete\",\n      Timestamps: [2021-10-17 13:05:00 +0000 UTC,2021-10-17 13:04:00 +0000 UTC],\n      Values: [12,14]\n    },{\n      Id: \"id_1905388747193831650\",\n      Label: \"NumberOfMessagesDeleted\",\n      StatusCode: \"Complete\",\n      Timestamps: [2021-10-17 13:05:00 +0000 UTC,2021-10-17 13:04:00 +0000 UTC],\n      Values: [10148,9876]\n    }]\n}","time":"2021-10-17T13:19:46Z"}
{"level":"debug","msg":"Metrics scraped.","time":"2021-10-17T13:19:46Z"}
```
