### ISSUE TITLE
[BUG] Tag labels are not being added automatically to metrics for AWS keyspace / cassandra service

### ISSUE THREAD

**Issue by bdeore** [prometheus-community/yet-another-cloudwatch-exporter#814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Here's my config: 
````
      apiVersion: v1alpha1
      sts-region: us-east-1
      discovery:
        exportedTagsOnMetrics:
          cassandra:
            - business_service
            - component
        jobs:
          - type: cassandra
            regions:
              - us-east-1
            roles:
              - roleArn: <redacted>
            searchTags:
              - key: environment
                value: dev
            metrics:
              - name: ProvisionedReadCapacityUnits
                statistics:
                  - Average
                  - Minimum
                  - Maximum
              - name: ProvisionedWriteCapacityUnits
                statistics:
                  - Average
                  - Minimum
                  - Maximum
````

### Expected Behavior

`aws_cassandra_provisioned_read_capacity_units_average` metric should be tagged with business_service and component tag. these tags are missing.
