### ISSUE TITLE
[BUG] Edge Lambda scraping throw error when adding multiple regions in config

### ISSUE THREAD

**Issue by tyagian** [prometheus-community/yet-another-cloudwatch-exporter#876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have EKS cluster deployed in eu-central-1 so 
openID is https://oidc.eks.eu-central-1.amazonaws.com/id/xxxxxxxxxxxx

and IAM role policy have these permissions. 

`{
    "Statement": [
        {
            "Action": [
                "tag:GetResources",
                "cloudwatch:*",
                "cloudwatch:GetMetricData",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:ListMetrics",
                "lambda:Get*",
                "lambda:List*",
                "lambda:Describe*",
                "lambda:TagResource",
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": "yacemetricsExporterPolicy"
        }
    ],
    "Version": "2012-10-17"
}`

Trust relationship in IAM role: 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::xxxxxx:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/xxxxxxx1"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.eu-central-1.amazonaws.com/id/1xxxxxxxxx1:sub": "system:serviceaccount:yace-exporter:yace-exporter"
                }

            }
        }
    ]
}
```
In yace helm value file, service account is defined as: 

```
serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::00xxxxxxx:role/yace_exporter_role
  labels: {}
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: yace
```

Now, when I am adding Lambda metrics in config section of helm values.yaml file: 

```
config: |-
  apiVersion: v1alpha1
  discovery:
    jobs:
    - regions: 
        - eu-central-1
        - us-west-1
        - us-west-2
        - us-east-1
        - us-east-2
      type: lambda
      enableMetricData: true
      metrics:
        - name: Duration
          statistics:
          - Maximum
          - Minimum
          - Average
          period: 300
          length: 3600
        - name: Invocations
          statistics:
          - Sum
          period: 300
          length: 3600
        - name: Throttles
          statistics:
          - Sum
          period: 300
          length: 3600
        - name: Errors
          statistics:
          - Sum
          period: 300
          length: 3600
        - name: ConcurrentExecutions
          statistics:
          - Sum
          period: 300
          length: 3600
```

I get error: 

`{"level":"error","msg":"Resource tag list is empty (in 0xxxxxxxxx). Tags must be defined for lambda to be discovered.","time":"2023-03-22T21:56:10Z"}`

but when I keep only  - eu-central-1 under regions in config, I don't get any such error.
I have Prometheus running in EKS cluster on eu-central-1. 

This is the IAM policy for OIDC. 

```
 {
  name = "rcw_yace_exporter_role"

  assume_role_policy = jsonencode({
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::xxxx:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/xxxx"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.eu-central-1.amazonaws.com/id/xxxx:sub": "system:serviceaccount:yace-exporter:yace-exporter"
                }
            }
        }
    ]
  })
```

How do I know where I am lacking permissions to get rid from this error? I am also using edge Lambda. 
- User permissions or IAM role?

### Expected Behavior

Expected not to get any error. 

### Steps To Reproduce

explained above
